version: '3'
services:

  project:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1




  postgres:
    image: postgres:14-alpine3.16
    environment:
      - POSTGRES_USER=vijay
      - POSTGRES_PASSWORD=zmxmcmvbn
      - POSTGRES_DB=echo_rest
    ports:
      - "5433:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./database/postgres/:/var/lib/postgresql



