version: '3'
services:




  postgres:
    image: postgres:14-alpine3.16
    container_name: postgres
    environment:
      - POSTGRES_USER=vijay
      - POSTGRES_PASSWORD=zmxmcmvbn
      - POSTGRES_DB=echo_rest
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./database/postgres/:/var/lib/postgresql
    


  app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: echo
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - "postgres:database"